# Generated by Django 3.1.5 on 2021-01-25 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='P_aluno',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_Pessoas.pessoa')),
                ('cpf', models.CharField(max_length=11)),
                ('turma', models.CharField(max_length=20)),
            ],
            bases=('app_Pessoas.pessoa',),
        ),
        migrations.CreateModel(
            name='P_professor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_Pessoas.pessoa')),
                ('cpf', models.CharField(max_length=11)),
                ('titulo', models.CharField(max_length=20)),
            ],
            bases=('app_Pessoas.pessoa',),
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('aluno', models.ManyToManyField(related_name='disc_aluno', to='app_Pessoas.P_aluno')),
                ('professor', models.ManyToManyField(related_name='disc_prof', to='app_Pessoas.P_professor')),
            ],
        ),
    ]
