# Generated by Django 3.1.5 on 2021-01-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='aluno',
            field=models.ManyToManyField(related_name='disciplinaAluno', to='app_Pessoas.Pessoa'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='professor',
            field=models.ManyToManyField(related_name='disciplinaProf', to='app_Pessoas.Pessoa'),
        ),
    ]
