# Generated by Django 3.1.5 on 2021-01-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Pessoas', '0002_auto_20210125_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='aluno',
            field=models.ManyToManyField(related_name='disciplinaAluno', to='app_Pessoas.P_aluno'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='professor',
            field=models.ManyToManyField(related_name='disciplinaProf', to='app_Pessoas.P_professor'),
        ),
    ]
