# Generated by Django 3.1.5 on 2021-03-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Pessoas', '0002_auto_20210308_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p_aluno',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='p_professor',
            name='cpf',
        ),
        migrations.AddField(
            model_name='p_aluno',
            name='matricula_aluno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='p_professor',
            name='matricula_prof',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
    ]
