# Generated by Django 3.1.5 on 2021-04-08 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Pessoas', '0003_auto_20210308_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='cpf',
        ),
    ]
