# Generated by Django 3.1.5 on 2021-01-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Pessoas', '0003_auto_20210126_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='aluno',
            field=models.ManyToManyField(related_name='discAluno', to='app_Pessoas.P_aluno'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='professor',
            field=models.ManyToManyField(related_name='discProf', to='app_Pessoas.P_professor'),
        ),
    ]
