# Generated by Django 3.1.5 on 2021-01-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Pessoas', '0004_auto_20210126_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='aluno',
            field=models.ManyToManyField(related_name='discAluno', to='app_Pessoas.Pessoa'),
        ),
    ]
