# Generated by Django 3.1.5 on 2021-01-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Pessoas', '0005_auto_20210126_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='professor',
            field=models.ManyToManyField(related_name='discProf', to='app_Pessoas.Pessoa'),
        ),
    ]
