# Generated by Django 3.1.5 on 2021-01-29 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Pessoas', '0007_pessoa_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='slug',
        ),
    ]
