# Generated by Django 3.1.5 on 2021-02-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativa', models.IntegerField(choices=[(1, 'CPF'), (2, 'RG'), (3, 'CNH')], default=1)),
                ('pergunta', models.CharField(max_length=100)),
                ('resposta', models.CharField(max_length=100)),
                ('gabarito', models.CharField(max_length=20)),
            ],
        ),
    ]
