# Generated by Django 3.1.5 on 2021-02-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=100)),
                ('alternativa', models.IntegerField(choices=[(1, '1-CPF'), (2, '2-RG'), (3, '3-CNH')], default=1)),
                ('alternativa2', models.CharField(choices=[('CPF', 'cpf'), ('RG', 'rg'), ('CNH', 'cnh')], default='RG', max_length=20)),
                ('resposta', models.CharField(max_length=100)),
                ('gabarito', models.CharField(max_length=20)),
            ],
        ),
    ]
