# Generated by Django 3.1.5 on 2021-02-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gab',
            name='alternativa2',
            field=models.CharField(choices=[('CPF', 'CPF'), ('RG', 'RG'), ('CNH', 'CNH')], default='RG', max_length=20),
        ),
        migrations.AlterField(
            model_name='gab',
            name='alternativa',
            field=models.IntegerField(choices=[(1, '1-CPF'), (2, '2-RG'), (3, '3-CNH')], default=1),
        ),
    ]
