# Generated by Django 3.1.5 on 2021-02-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gab',
            name='resposta',
            field=models.CharField(max_length=10),
        ),
    ]
