# Generated by Django 3.1.5 on 2021-02-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gab',
            name='resposta',
            field=models.BooleanField(default=True),
        ),
    ]
