# Generated by Django 3.1.5 on 2021-02-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_questions', '0002_gab_resposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gab',
            name='resposta',
            field=models.CharField(max_length=100),
        ),
    ]
